# Generated by Django 3.0.8 on 2020-11-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_name', models.CharField(max_length=50)),
                ('art_description', models.CharField(max_length=400)),
                ('art_image', models.ImageField(default='', upload_to='ued_web/images')),
            ],
        ),
        migrations.CreateModel(
            name='ux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ux_name', models.CharField(max_length=50)),
                ('ux_description', models.CharField(max_length=400)),
                ('ux_image', models.ImageField(default='', upload_to='ued_web/images')),
            ],
        ),
    ]
