# Generated by Django 3.0.8 on 2020-11-05 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ued_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='art',
            new_name='artwork',
        ),
        migrations.RenameModel(
            old_name='ux',
            new_name='uxwork',
        ),
    ]
