# Generated by Django 3.0.8 on 2020-11-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ued_web', '0004_auto_20201105_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uxwork',
            name='ux_image',
            field=models.ImageField(default='', upload_to='static/home'),
        ),
    ]
