# Generated by Django 3.0.8 on 2020-11-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ued_web', '0006_auto_20201105_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='art_image',
            field=models.ImageField(default='', upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='uxwork',
            name='ux_image',
            field=models.ImageField(default='', upload_to='media/images'),
        ),
    ]
